version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  pkg-style:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Cached CI dependencies
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}
            - v1-deps-{{ .Branch }}
            - v1-deps-
      - run:
          name: CI dependencies installation
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r .circleci/requirements.txt
      - save_cache:
          when: always
          paths:
            - "venv"
          key: v1-deps-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}

      - run:
          name: Flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            flake8 ./

workflows:
  version: 2.1
  build:
    jobs:
      - pkg-style
